/** This file was autogenerated by the mpc_planner_solver package at 10:08PM on November 03, 2025*/
#ifndef __MPC_PLANNER_GENERATED_H__
#define __MPC_PLANNER_GENERATED_H__

#include <Solver.h>

namespace MPCPlanner{

double getForcesOutput(const Solver_output& output, const int k, const int var_index);
void loadForcesWarmstart(Solver_params& params, const Solver_output& output);
	void setForcesReinitialize(Solver_params& params, const bool value);
}
#endif