/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[243] = {239, 1, 0, 239, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238};
static const casadi_int casadi_s4[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};

/* Solver_constr_h_fun:(i0[6],i1[2],i2[],i3[239])->(o0[36]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][81] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][82] : 0;
  a3=arg[0]? arg[0][1] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][83] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][84] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][85] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][86] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3]? arg[3][87] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][88] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][89] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3]? arg[3][90] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][91] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][92] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3]? arg[3][93] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][94] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][95] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[3]? arg[3][96] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][97] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][98] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[3]? arg[3][99] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][100] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][101] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[3]? arg[3][102] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][103] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][104] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[3]? arg[3][105] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][106] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][107] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[3]? arg[3][108] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][109] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][110] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[3]? arg[3][111] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][112] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][113] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[3]? arg[3][114] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][115] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][116] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a2=cos(a0);
  a4=arg[3]? arg[3][118] : 0;
  a5=(a2*a4);
  a5=(a1+a5);
  a6=arg[3]? arg[3][119] : 0;
  a5=(a5-a6);
  a6=arg[3]? arg[3][121] : 0;
  a7=cos(a6);
  a8=arg[3]? arg[3][122] : 0;
  a9=arg[3]? arg[3][124] : 0;
  a10=sqrt(a9);
  a8=(a8*a10);
  a10=arg[3]? arg[3][117] : 0;
  a11=(a8+a10);
  a12=arg[3]? arg[3][125] : 0;
  a11=(a11+a12);
  a8=(a8+a10);
  a8=(a8+a12);
  a11=(a11*a8);
  a8=(a7/a11);
  a13=(a8*a7);
  a14=sin(a6);
  a15=arg[3]? arg[3][123] : 0;
  a9=sqrt(a9);
  a15=(a15*a9);
  a9=(a15+a10);
  a9=(a9+a12);
  a15=(a15+a10);
  a15=(a15+a12);
  a9=(a9*a15);
  a15=(a14/a9);
  a12=(a15*a14);
  a13=(a13+a12);
  a13=(a5*a13);
  a12=sin(a0);
  a16=(a12*a4);
  a16=(a3+a16);
  a17=arg[3]? arg[3][120] : 0;
  a16=(a16-a17);
  a17=cos(a6);
  a9=(a17/a9);
  a14=(a9*a14);
  a6=sin(a6);
  a11=(a6/a11);
  a7=(a11*a7);
  a14=(a14-a7);
  a14=(a16*a14);
  a13=(a13+a14);
  a13=(a13*a5);
  a15=(a15*a17);
  a8=(a8*a6);
  a15=(a15-a8);
  a5=(a5*a15);
  a11=(a11*a6);
  a9=(a9*a17);
  a11=(a11+a9);
  a11=(a16*a11);
  a5=(a5+a11);
  a5=(a5*a16);
  a13=(a13+a5);
  if (res[0]!=0) res[0][12]=a13;
  a13=(a2*a4);
  a13=(a1+a13);
  a5=arg[3]? arg[3][126] : 0;
  a13=(a13-a5);
  a5=arg[3]? arg[3][128] : 0;
  a16=cos(a5);
  a11=arg[3]? arg[3][129] : 0;
  a9=arg[3]? arg[3][131] : 0;
  a17=sqrt(a9);
  a11=(a11*a17);
  a17=(a11+a10);
  a6=arg[3]? arg[3][132] : 0;
  a17=(a17+a6);
  a11=(a11+a10);
  a11=(a11+a6);
  a17=(a17*a11);
  a11=(a16/a17);
  a15=(a11*a16);
  a8=sin(a5);
  a14=arg[3]? arg[3][130] : 0;
  a9=sqrt(a9);
  a14=(a14*a9);
  a9=(a14+a10);
  a9=(a9+a6);
  a14=(a14+a10);
  a14=(a14+a6);
  a9=(a9*a14);
  a14=(a8/a9);
  a6=(a14*a8);
  a15=(a15+a6);
  a15=(a13*a15);
  a6=(a12*a4);
  a6=(a3+a6);
  a7=arg[3]? arg[3][127] : 0;
  a6=(a6-a7);
  a7=cos(a5);
  a9=(a7/a9);
  a8=(a9*a8);
  a5=sin(a5);
  a17=(a5/a17);
  a16=(a17*a16);
  a8=(a8-a16);
  a8=(a6*a8);
  a15=(a15+a8);
  a15=(a15*a13);
  a14=(a14*a7);
  a11=(a11*a5);
  a14=(a14-a11);
  a13=(a13*a14);
  a17=(a17*a5);
  a9=(a9*a7);
  a17=(a17+a9);
  a17=(a6*a17);
  a13=(a13+a17);
  a13=(a13*a6);
  a15=(a15+a13);
  if (res[0]!=0) res[0][13]=a15;
  a15=(a2*a4);
  a15=(a1+a15);
  a13=arg[3]? arg[3][133] : 0;
  a15=(a15-a13);
  a13=arg[3]? arg[3][135] : 0;
  a6=cos(a13);
  a17=arg[3]? arg[3][136] : 0;
  a9=arg[3]? arg[3][138] : 0;
  a7=sqrt(a9);
  a17=(a17*a7);
  a7=(a17+a10);
  a5=arg[3]? arg[3][139] : 0;
  a7=(a7+a5);
  a17=(a17+a10);
  a17=(a17+a5);
  a7=(a7*a17);
  a17=(a6/a7);
  a14=(a17*a6);
  a11=sin(a13);
  a8=arg[3]? arg[3][137] : 0;
  a9=sqrt(a9);
  a8=(a8*a9);
  a9=(a8+a10);
  a9=(a9+a5);
  a8=(a8+a10);
  a8=(a8+a5);
  a9=(a9*a8);
  a8=(a11/a9);
  a5=(a8*a11);
  a14=(a14+a5);
  a14=(a15*a14);
  a5=(a12*a4);
  a5=(a3+a5);
  a16=arg[3]? arg[3][134] : 0;
  a5=(a5-a16);
  a16=cos(a13);
  a9=(a16/a9);
  a11=(a9*a11);
  a13=sin(a13);
  a7=(a13/a7);
  a6=(a7*a6);
  a11=(a11-a6);
  a11=(a5*a11);
  a14=(a14+a11);
  a14=(a14*a15);
  a8=(a8*a16);
  a17=(a17*a13);
  a8=(a8-a17);
  a15=(a15*a8);
  a7=(a7*a13);
  a9=(a9*a16);
  a7=(a7+a9);
  a7=(a5*a7);
  a15=(a15+a7);
  a15=(a15*a5);
  a14=(a14+a15);
  if (res[0]!=0) res[0][14]=a14;
  a14=(a2*a4);
  a14=(a1+a14);
  a15=arg[3]? arg[3][140] : 0;
  a14=(a14-a15);
  a15=arg[3]? arg[3][142] : 0;
  a5=cos(a15);
  a7=arg[3]? arg[3][143] : 0;
  a9=arg[3]? arg[3][145] : 0;
  a16=sqrt(a9);
  a7=(a7*a16);
  a16=(a7+a10);
  a13=arg[3]? arg[3][146] : 0;
  a16=(a16+a13);
  a7=(a7+a10);
  a7=(a7+a13);
  a16=(a16*a7);
  a7=(a5/a16);
  a8=(a7*a5);
  a17=sin(a15);
  a11=arg[3]? arg[3][144] : 0;
  a9=sqrt(a9);
  a11=(a11*a9);
  a9=(a11+a10);
  a9=(a9+a13);
  a11=(a11+a10);
  a11=(a11+a13);
  a9=(a9*a11);
  a11=(a17/a9);
  a13=(a11*a17);
  a8=(a8+a13);
  a8=(a14*a8);
  a13=(a12*a4);
  a13=(a3+a13);
  a6=arg[3]? arg[3][141] : 0;
  a13=(a13-a6);
  a6=cos(a15);
  a9=(a6/a9);
  a17=(a9*a17);
  a15=sin(a15);
  a16=(a15/a16);
  a5=(a16*a5);
  a17=(a17-a5);
  a17=(a13*a17);
  a8=(a8+a17);
  a8=(a8*a14);
  a11=(a11*a6);
  a7=(a7*a15);
  a11=(a11-a7);
  a14=(a14*a11);
  a16=(a16*a15);
  a9=(a9*a6);
  a16=(a16+a9);
  a16=(a13*a16);
  a14=(a14+a16);
  a14=(a14*a13);
  a8=(a8+a14);
  if (res[0]!=0) res[0][15]=a8;
  a8=(a2*a4);
  a8=(a1+a8);
  a14=arg[3]? arg[3][147] : 0;
  a8=(a8-a14);
  a14=arg[3]? arg[3][149] : 0;
  a13=cos(a14);
  a16=arg[3]? arg[3][150] : 0;
  a9=arg[3]? arg[3][152] : 0;
  a6=sqrt(a9);
  a16=(a16*a6);
  a6=(a16+a10);
  a15=arg[3]? arg[3][153] : 0;
  a6=(a6+a15);
  a16=(a16+a10);
  a16=(a16+a15);
  a6=(a6*a16);
  a16=(a13/a6);
  a11=(a16*a13);
  a7=sin(a14);
  a17=arg[3]? arg[3][151] : 0;
  a9=sqrt(a9);
  a17=(a17*a9);
  a9=(a17+a10);
  a9=(a9+a15);
  a17=(a17+a10);
  a17=(a17+a15);
  a9=(a9*a17);
  a17=(a7/a9);
  a15=(a17*a7);
  a11=(a11+a15);
  a11=(a8*a11);
  a15=(a12*a4);
  a15=(a3+a15);
  a5=arg[3]? arg[3][148] : 0;
  a15=(a15-a5);
  a5=cos(a14);
  a9=(a5/a9);
  a7=(a9*a7);
  a14=sin(a14);
  a6=(a14/a6);
  a13=(a6*a13);
  a7=(a7-a13);
  a7=(a15*a7);
  a11=(a11+a7);
  a11=(a11*a8);
  a17=(a17*a5);
  a16=(a16*a14);
  a17=(a17-a16);
  a8=(a8*a17);
  a6=(a6*a14);
  a9=(a9*a5);
  a6=(a6+a9);
  a6=(a15*a6);
  a8=(a8+a6);
  a8=(a8*a15);
  a11=(a11+a8);
  if (res[0]!=0) res[0][16]=a11;
  a11=(a2*a4);
  a11=(a1+a11);
  a8=arg[3]? arg[3][154] : 0;
  a11=(a11-a8);
  a8=arg[3]? arg[3][156] : 0;
  a15=cos(a8);
  a6=arg[3]? arg[3][157] : 0;
  a9=arg[3]? arg[3][159] : 0;
  a5=sqrt(a9);
  a6=(a6*a5);
  a5=(a6+a10);
  a14=arg[3]? arg[3][160] : 0;
  a5=(a5+a14);
  a6=(a6+a10);
  a6=(a6+a14);
  a5=(a5*a6);
  a6=(a15/a5);
  a17=(a6*a15);
  a16=sin(a8);
  a7=arg[3]? arg[3][158] : 0;
  a9=sqrt(a9);
  a7=(a7*a9);
  a9=(a7+a10);
  a9=(a9+a14);
  a7=(a7+a10);
  a7=(a7+a14);
  a9=(a9*a7);
  a7=(a16/a9);
  a14=(a7*a16);
  a17=(a17+a14);
  a17=(a11*a17);
  a14=(a12*a4);
  a14=(a3+a14);
  a13=arg[3]? arg[3][155] : 0;
  a14=(a14-a13);
  a13=cos(a8);
  a9=(a13/a9);
  a16=(a9*a16);
  a8=sin(a8);
  a5=(a8/a5);
  a15=(a5*a15);
  a16=(a16-a15);
  a16=(a14*a16);
  a17=(a17+a16);
  a17=(a17*a11);
  a7=(a7*a13);
  a6=(a6*a8);
  a7=(a7-a6);
  a11=(a11*a7);
  a5=(a5*a8);
  a9=(a9*a13);
  a5=(a5+a9);
  a5=(a14*a5);
  a11=(a11+a5);
  a11=(a11*a14);
  a17=(a17+a11);
  if (res[0]!=0) res[0][17]=a17;
  a17=(a2*a4);
  a17=(a1+a17);
  a11=arg[3]? arg[3][161] : 0;
  a17=(a17-a11);
  a11=arg[3]? arg[3][163] : 0;
  a14=cos(a11);
  a5=arg[3]? arg[3][164] : 0;
  a9=arg[3]? arg[3][166] : 0;
  a13=sqrt(a9);
  a5=(a5*a13);
  a13=(a5+a10);
  a8=arg[3]? arg[3][167] : 0;
  a13=(a13+a8);
  a5=(a5+a10);
  a5=(a5+a8);
  a13=(a13*a5);
  a5=(a14/a13);
  a7=(a5*a14);
  a6=sin(a11);
  a16=arg[3]? arg[3][165] : 0;
  a9=sqrt(a9);
  a16=(a16*a9);
  a9=(a16+a10);
  a9=(a9+a8);
  a16=(a16+a10);
  a16=(a16+a8);
  a9=(a9*a16);
  a16=(a6/a9);
  a8=(a16*a6);
  a7=(a7+a8);
  a7=(a17*a7);
  a8=(a12*a4);
  a8=(a3+a8);
  a15=arg[3]? arg[3][162] : 0;
  a8=(a8-a15);
  a15=cos(a11);
  a9=(a15/a9);
  a6=(a9*a6);
  a11=sin(a11);
  a13=(a11/a13);
  a14=(a13*a14);
  a6=(a6-a14);
  a6=(a8*a6);
  a7=(a7+a6);
  a7=(a7*a17);
  a16=(a16*a15);
  a5=(a5*a11);
  a16=(a16-a5);
  a17=(a17*a16);
  a13=(a13*a11);
  a9=(a9*a15);
  a13=(a13+a9);
  a13=(a8*a13);
  a17=(a17+a13);
  a17=(a17*a8);
  a7=(a7+a17);
  if (res[0]!=0) res[0][18]=a7;
  a7=(a2*a4);
  a7=(a1+a7);
  a17=arg[3]? arg[3][168] : 0;
  a7=(a7-a17);
  a17=arg[3]? arg[3][170] : 0;
  a8=cos(a17);
  a13=arg[3]? arg[3][171] : 0;
  a9=arg[3]? arg[3][173] : 0;
  a15=sqrt(a9);
  a13=(a13*a15);
  a15=(a13+a10);
  a11=arg[3]? arg[3][174] : 0;
  a15=(a15+a11);
  a13=(a13+a10);
  a13=(a13+a11);
  a15=(a15*a13);
  a13=(a8/a15);
  a16=(a13*a8);
  a5=sin(a17);
  a6=arg[3]? arg[3][172] : 0;
  a9=sqrt(a9);
  a6=(a6*a9);
  a9=(a6+a10);
  a9=(a9+a11);
  a6=(a6+a10);
  a6=(a6+a11);
  a9=(a9*a6);
  a6=(a5/a9);
  a11=(a6*a5);
  a16=(a16+a11);
  a16=(a7*a16);
  a11=(a12*a4);
  a11=(a3+a11);
  a14=arg[3]? arg[3][169] : 0;
  a11=(a11-a14);
  a14=cos(a17);
  a9=(a14/a9);
  a5=(a9*a5);
  a17=sin(a17);
  a15=(a17/a15);
  a8=(a15*a8);
  a5=(a5-a8);
  a5=(a11*a5);
  a16=(a16+a5);
  a16=(a16*a7);
  a6=(a6*a14);
  a13=(a13*a17);
  a6=(a6-a13);
  a7=(a7*a6);
  a15=(a15*a17);
  a9=(a9*a14);
  a15=(a15+a9);
  a15=(a11*a15);
  a7=(a7+a15);
  a7=(a7*a11);
  a16=(a16+a7);
  if (res[0]!=0) res[0][19]=a16;
  a16=(a2*a4);
  a16=(a1+a16);
  a7=arg[3]? arg[3][175] : 0;
  a16=(a16-a7);
  a7=arg[3]? arg[3][177] : 0;
  a11=cos(a7);
  a15=arg[3]? arg[3][178] : 0;
  a9=arg[3]? arg[3][180] : 0;
  a14=sqrt(a9);
  a15=(a15*a14);
  a14=(a15+a10);
  a17=arg[3]? arg[3][181] : 0;
  a14=(a14+a17);
  a15=(a15+a10);
  a15=(a15+a17);
  a14=(a14*a15);
  a15=(a11/a14);
  a6=(a15*a11);
  a13=sin(a7);
  a5=arg[3]? arg[3][179] : 0;
  a9=sqrt(a9);
  a5=(a5*a9);
  a9=(a5+a10);
  a9=(a9+a17);
  a5=(a5+a10);
  a5=(a5+a17);
  a9=(a9*a5);
  a5=(a13/a9);
  a17=(a5*a13);
  a6=(a6+a17);
  a6=(a16*a6);
  a17=(a12*a4);
  a17=(a3+a17);
  a8=arg[3]? arg[3][176] : 0;
  a17=(a17-a8);
  a8=cos(a7);
  a9=(a8/a9);
  a13=(a9*a13);
  a7=sin(a7);
  a14=(a7/a14);
  a11=(a14*a11);
  a13=(a13-a11);
  a13=(a17*a13);
  a6=(a6+a13);
  a6=(a6*a16);
  a5=(a5*a8);
  a15=(a15*a7);
  a5=(a5-a15);
  a16=(a16*a5);
  a14=(a14*a7);
  a9=(a9*a8);
  a14=(a14+a9);
  a14=(a17*a14);
  a16=(a16+a14);
  a16=(a16*a17);
  a6=(a6+a16);
  if (res[0]!=0) res[0][20]=a6;
  a6=(a2*a4);
  a6=(a1+a6);
  a16=arg[3]? arg[3][182] : 0;
  a6=(a6-a16);
  a16=arg[3]? arg[3][184] : 0;
  a17=cos(a16);
  a14=arg[3]? arg[3][185] : 0;
  a9=arg[3]? arg[3][187] : 0;
  a8=sqrt(a9);
  a14=(a14*a8);
  a8=(a14+a10);
  a7=arg[3]? arg[3][188] : 0;
  a8=(a8+a7);
  a14=(a14+a10);
  a14=(a14+a7);
  a8=(a8*a14);
  a14=(a17/a8);
  a5=(a14*a17);
  a15=sin(a16);
  a13=arg[3]? arg[3][186] : 0;
  a9=sqrt(a9);
  a13=(a13*a9);
  a9=(a13+a10);
  a9=(a9+a7);
  a13=(a13+a10);
  a13=(a13+a7);
  a9=(a9*a13);
  a13=(a15/a9);
  a7=(a13*a15);
  a5=(a5+a7);
  a5=(a6*a5);
  a7=(a12*a4);
  a7=(a3+a7);
  a11=arg[3]? arg[3][183] : 0;
  a7=(a7-a11);
  a11=cos(a16);
  a9=(a11/a9);
  a15=(a9*a15);
  a16=sin(a16);
  a8=(a16/a8);
  a17=(a8*a17);
  a15=(a15-a17);
  a15=(a7*a15);
  a5=(a5+a15);
  a5=(a5*a6);
  a13=(a13*a11);
  a14=(a14*a16);
  a13=(a13-a14);
  a6=(a6*a13);
  a8=(a8*a16);
  a9=(a9*a11);
  a8=(a8+a9);
  a8=(a7*a8);
  a6=(a6+a8);
  a6=(a6*a7);
  a5=(a5+a6);
  if (res[0]!=0) res[0][21]=a5;
  a5=(a2*a4);
  a5=(a1+a5);
  a6=arg[3]? arg[3][189] : 0;
  a5=(a5-a6);
  a6=arg[3]? arg[3][191] : 0;
  a7=cos(a6);
  a8=arg[3]? arg[3][192] : 0;
  a9=arg[3]? arg[3][194] : 0;
  a11=sqrt(a9);
  a8=(a8*a11);
  a11=(a8+a10);
  a16=arg[3]? arg[3][195] : 0;
  a11=(a11+a16);
  a8=(a8+a10);
  a8=(a8+a16);
  a11=(a11*a8);
  a8=(a7/a11);
  a13=(a8*a7);
  a14=sin(a6);
  a15=arg[3]? arg[3][193] : 0;
  a9=sqrt(a9);
  a15=(a15*a9);
  a9=(a15+a10);
  a9=(a9+a16);
  a15=(a15+a10);
  a15=(a15+a16);
  a9=(a9*a15);
  a15=(a14/a9);
  a16=(a15*a14);
  a13=(a13+a16);
  a13=(a5*a13);
  a16=(a12*a4);
  a16=(a3+a16);
  a17=arg[3]? arg[3][190] : 0;
  a16=(a16-a17);
  a17=cos(a6);
  a9=(a17/a9);
  a14=(a9*a14);
  a6=sin(a6);
  a11=(a6/a11);
  a7=(a11*a7);
  a14=(a14-a7);
  a14=(a16*a14);
  a13=(a13+a14);
  a13=(a13*a5);
  a15=(a15*a17);
  a8=(a8*a6);
  a15=(a15-a8);
  a5=(a5*a15);
  a11=(a11*a6);
  a9=(a9*a17);
  a11=(a11+a9);
  a11=(a16*a11);
  a5=(a5+a11);
  a5=(a5*a16);
  a13=(a13+a5);
  if (res[0]!=0) res[0][22]=a13;
  a2=(a2*a4);
  a2=(a1+a2);
  a13=arg[3]? arg[3][196] : 0;
  a2=(a2-a13);
  a13=arg[3]? arg[3][198] : 0;
  a5=cos(a13);
  a16=arg[3]? arg[3][199] : 0;
  a11=arg[3]? arg[3][201] : 0;
  a9=sqrt(a11);
  a16=(a16*a9);
  a9=(a16+a10);
  a17=arg[3]? arg[3][202] : 0;
  a9=(a9+a17);
  a16=(a16+a10);
  a16=(a16+a17);
  a9=(a9*a16);
  a16=(a5/a9);
  a6=(a16*a5);
  a15=sin(a13);
  a8=arg[3]? arg[3][200] : 0;
  a11=sqrt(a11);
  a8=(a8*a11);
  a11=(a8+a10);
  a11=(a11+a17);
  a8=(a8+a10);
  a8=(a8+a17);
  a11=(a11*a8);
  a8=(a15/a11);
  a17=(a8*a15);
  a6=(a6+a17);
  a6=(a2*a6);
  a12=(a12*a4);
  a12=(a3+a12);
  a17=arg[3]? arg[3][197] : 0;
  a12=(a12-a17);
  a17=cos(a13);
  a11=(a17/a11);
  a15=(a11*a15);
  a13=sin(a13);
  a9=(a13/a9);
  a5=(a9*a5);
  a15=(a15-a5);
  a15=(a12*a15);
  a6=(a6+a15);
  a6=(a6*a2);
  a8=(a8*a17);
  a16=(a16*a13);
  a8=(a8-a16);
  a2=(a2*a8);
  a9=(a9*a13);
  a11=(a11*a17);
  a9=(a9+a11);
  a9=(a12*a9);
  a2=(a2+a9);
  a2=(a2*a12);
  a6=(a6+a2);
  if (res[0]!=0) res[0][23]=a6;
  a6=arg[3]? arg[3][203] : 0;
  a2=cos(a0);
  a2=(a2*a4);
  a1=(a1+a2);
  a6=(a6*a1);
  a2=arg[3]? arg[3][204] : 0;
  a0=sin(a0);
  a0=(a0*a4);
  a3=(a3+a0);
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][205] : 0;
  a0=arg[0]? arg[0][5] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][24]=a6;
  a6=arg[3]? arg[3][206] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][207] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][208] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][25]=a6;
  a6=arg[3]? arg[3][209] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][210] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][211] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][26]=a6;
  a6=arg[3]? arg[3][212] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][213] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][214] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][27]=a6;
  a6=arg[3]? arg[3][215] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][216] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][217] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][28]=a6;
  a6=arg[3]? arg[3][218] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][219] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][220] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][29]=a6;
  a6=arg[3]? arg[3][221] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][222] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][223] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][30]=a6;
  a6=arg[3]? arg[3][224] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][225] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][226] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][31]=a6;
  a6=arg[3]? arg[3][227] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][228] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][229] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][32]=a6;
  a6=arg[3]? arg[3][230] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][231] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][232] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][33]=a6;
  a6=arg[3]? arg[3][233] : 0;
  a6=(a6*a1);
  a2=arg[3]? arg[3][234] : 0;
  a2=(a2*a3);
  a6=(a6+a2);
  a2=arg[3]? arg[3][235] : 0;
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][34]=a6;
  a6=arg[3]? arg[3][236] : 0;
  a6=(a6*a1);
  a1=arg[3]? arg[3][237] : 0;
  a1=(a1*a3);
  a6=(a6+a1);
  a1=arg[3]? arg[3][238] : 0;
  a1=(a1+a0);
  a6=(a6-a1);
  if (res[0]!=0) res[0][35]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Solver_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Solver_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
