
typedef struct{
	
	float VIOLATION_COST_POWER;
	int COLLISION_CHECK_RADIUS;
	int HURISTIC_TYPE;
	bool IS_ITERATION_SYMMETRIC;
	
	bool DO_JOINTSTATESPACE_LOGGING;
	int JOINTSTATESPACE_LOGGING_METHOD;
	int JOINTSTATESPACE_LOGGING_RAD;
	
	int ITERATION_TYPE;
	int MAX_ITERATION_COUNT;
	int MIN_ITERATION_COUNT;
	int CONVERGENCE_CYCLE_COUNT;
	
	int PENALTY_WEIGHT_INCREMENT_METHOD;
	int PENALTY_BIN_SEARCH_MAXSTEPS;
	float PENALTY_BIN_SEARCH_THRESH;
	//float PENALTY_INCREMENT_MULT_FAC;
	//vector<float> PenaltyWeightParams;
	
	int STATIC_OBSTACLE_INFLATION_RADIUS;
	
	//vector<EnvNAV3DXYT2Dpt_t> ObstacleCenters;
	
} GlobalParams_EnvNAV3DXYT;
