acceleration: 0
angular_velocity: 1
contour: 5
disc_0_decomp_0_a1: 203
disc_0_decomp_0_a2: 204
disc_0_decomp_0_b: 205
disc_0_decomp_10_a1: 233
disc_0_decomp_10_a2: 234
disc_0_decomp_10_b: 235
disc_0_decomp_11_a1: 236
disc_0_decomp_11_a2: 237
disc_0_decomp_11_b: 238
disc_0_decomp_1_a1: 206
disc_0_decomp_1_a2: 207
disc_0_decomp_1_b: 208
disc_0_decomp_2_a1: 209
disc_0_decomp_2_a2: 210
disc_0_decomp_2_b: 211
disc_0_decomp_3_a1: 212
disc_0_decomp_3_a2: 213
disc_0_decomp_3_b: 214
disc_0_decomp_4_a1: 215
disc_0_decomp_4_a2: 216
disc_0_decomp_4_b: 217
disc_0_decomp_5_a1: 218
disc_0_decomp_5_a2: 219
disc_0_decomp_5_b: 220
disc_0_decomp_6_a1: 221
disc_0_decomp_6_a2: 222
disc_0_decomp_6_b: 223
disc_0_decomp_7_a1: 224
disc_0_decomp_7_a2: 225
disc_0_decomp_7_b: 226
disc_0_decomp_8_a1: 227
disc_0_decomp_8_a2: 228
disc_0_decomp_8_b: 229
disc_0_decomp_9_a1: 230
disc_0_decomp_9_a2: 231
disc_0_decomp_9_b: 232
ego_disc_0_offset: 118
ego_disc_radius: 117
ellipsoid_obst_0_chi: 124
ellipsoid_obst_0_major: 122
ellipsoid_obst_0_minor: 123
ellipsoid_obst_0_psi: 121
ellipsoid_obst_0_r: 125
ellipsoid_obst_0_x: 119
ellipsoid_obst_0_y: 120
ellipsoid_obst_10_chi: 194
ellipsoid_obst_10_major: 192
ellipsoid_obst_10_minor: 193
ellipsoid_obst_10_psi: 191
ellipsoid_obst_10_r: 195
ellipsoid_obst_10_x: 189
ellipsoid_obst_10_y: 190
ellipsoid_obst_11_chi: 201
ellipsoid_obst_11_major: 199
ellipsoid_obst_11_minor: 200
ellipsoid_obst_11_psi: 198
ellipsoid_obst_11_r: 202
ellipsoid_obst_11_x: 196
ellipsoid_obst_11_y: 197
ellipsoid_obst_1_chi: 131
ellipsoid_obst_1_major: 129
ellipsoid_obst_1_minor: 130
ellipsoid_obst_1_psi: 128
ellipsoid_obst_1_r: 132
ellipsoid_obst_1_x: 126
ellipsoid_obst_1_y: 127
ellipsoid_obst_2_chi: 138
ellipsoid_obst_2_major: 136
ellipsoid_obst_2_minor: 137
ellipsoid_obst_2_psi: 135
ellipsoid_obst_2_r: 139
ellipsoid_obst_2_x: 133
ellipsoid_obst_2_y: 134
ellipsoid_obst_3_chi: 145
ellipsoid_obst_3_major: 143
ellipsoid_obst_3_minor: 144
ellipsoid_obst_3_psi: 142
ellipsoid_obst_3_r: 146
ellipsoid_obst_3_x: 140
ellipsoid_obst_3_y: 141
ellipsoid_obst_4_chi: 152
ellipsoid_obst_4_major: 150
ellipsoid_obst_4_minor: 151
ellipsoid_obst_4_psi: 149
ellipsoid_obst_4_r: 153
ellipsoid_obst_4_x: 147
ellipsoid_obst_4_y: 148
ellipsoid_obst_5_chi: 159
ellipsoid_obst_5_major: 157
ellipsoid_obst_5_minor: 158
ellipsoid_obst_5_psi: 156
ellipsoid_obst_5_r: 160
ellipsoid_obst_5_x: 154
ellipsoid_obst_5_y: 155
ellipsoid_obst_6_chi: 166
ellipsoid_obst_6_major: 164
ellipsoid_obst_6_minor: 165
ellipsoid_obst_6_psi: 163
ellipsoid_obst_6_r: 167
ellipsoid_obst_6_x: 161
ellipsoid_obst_6_y: 162
ellipsoid_obst_7_chi: 173
ellipsoid_obst_7_major: 171
ellipsoid_obst_7_minor: 172
ellipsoid_obst_7_psi: 170
ellipsoid_obst_7_r: 174
ellipsoid_obst_7_x: 168
ellipsoid_obst_7_y: 169
ellipsoid_obst_8_chi: 180
ellipsoid_obst_8_major: 178
ellipsoid_obst_8_minor: 179
ellipsoid_obst_8_psi: 177
ellipsoid_obst_8_r: 181
ellipsoid_obst_8_x: 175
ellipsoid_obst_8_y: 176
ellipsoid_obst_9_chi: 187
ellipsoid_obst_9_major: 185
ellipsoid_obst_9_minor: 186
ellipsoid_obst_9_psi: 184
ellipsoid_obst_9_r: 188
ellipsoid_obst_9_x: 182
ellipsoid_obst_9_y: 183
lag: 6
lin_constraint_0_a1: 81
lin_constraint_0_a2: 82
lin_constraint_0_b: 83
lin_constraint_10_a1: 111
lin_constraint_10_a2: 112
lin_constraint_10_b: 113
lin_constraint_11_a1: 114
lin_constraint_11_a2: 115
lin_constraint_11_b: 116
lin_constraint_1_a1: 84
lin_constraint_1_a2: 85
lin_constraint_1_b: 86
lin_constraint_2_a1: 87
lin_constraint_2_a2: 88
lin_constraint_2_b: 89
lin_constraint_3_a1: 90
lin_constraint_3_a2: 91
lin_constraint_3_b: 92
lin_constraint_4_a1: 93
lin_constraint_4_a2: 94
lin_constraint_4_b: 95
lin_constraint_5_a1: 96
lin_constraint_5_a2: 97
lin_constraint_5_b: 98
lin_constraint_6_a1: 99
lin_constraint_6_a2: 100
lin_constraint_6_b: 101
lin_constraint_7_a1: 102
lin_constraint_7_a2: 103
lin_constraint_7_b: 104
lin_constraint_8_a1: 105
lin_constraint_8_a2: 106
lin_constraint_8_b: 107
lin_constraint_9_a1: 108
lin_constraint_9_a2: 109
lin_constraint_9_b: 110
num parameters: 239
reference_velocity: 4
slack: 2
spline0_start: 17
spline1_start: 26
spline2_start: 35
spline3_start: 44
spline4_start: 53
spline5_start: 62
spline6_start: 71
spline7_start: 80
spline_x0_a: 9
spline_x0_b: 10
spline_x0_c: 11
spline_x0_d: 12
spline_x1_a: 18
spline_x1_b: 19
spline_x1_c: 20
spline_x1_d: 21
spline_x2_a: 27
spline_x2_b: 28
spline_x2_c: 29
spline_x2_d: 30
spline_x3_a: 36
spline_x3_b: 37
spline_x3_c: 38
spline_x3_d: 39
spline_x4_a: 45
spline_x4_b: 46
spline_x4_c: 47
spline_x4_d: 48
spline_x5_a: 54
spline_x5_b: 55
spline_x5_c: 56
spline_x5_d: 57
spline_x6_a: 63
spline_x6_b: 64
spline_x6_c: 65
spline_x6_d: 66
spline_x7_a: 72
spline_x7_b: 73
spline_x7_c: 74
spline_x7_d: 75
spline_y0_a: 13
spline_y0_b: 14
spline_y0_c: 15
spline_y0_d: 16
spline_y1_a: 22
spline_y1_b: 23
spline_y1_c: 24
spline_y1_d: 25
spline_y2_a: 31
spline_y2_b: 32
spline_y2_c: 33
spline_y2_d: 34
spline_y3_a: 40
spline_y3_b: 41
spline_y3_c: 42
spline_y3_d: 43
spline_y4_a: 49
spline_y4_b: 50
spline_y4_c: 51
spline_y4_d: 52
spline_y5_a: 58
spline_y5_b: 59
spline_y5_c: 60
spline_y5_d: 61
spline_y6_a: 67
spline_y6_b: 68
spline_y6_c: 69
spline_y6_d: 70
spline_y7_a: 76
spline_y7_b: 77
spline_y7_c: 78
spline_y7_d: 79
terminal_angle: 7
terminal_contouring: 8
velocity: 3
